import json
import os

generate_sftlf = True
regional = "y"
case_id = "v20240810"
# case_id = datetime.datetime.now().strftime("v%Y%m%d")

MIP = "cmip6"
exp = "amip"

user_notes = "Provenance and results"

# Set path to the required data (customized)
para_path = "/lcrc/group/acme/ac.szhang/acme_scratch/pcmdi_metrics/e3sm_setup"
output_path = "/lcrc/group/acme/ac.szhang/acme_scratch/data/pcmdi"
para_reg_file = "custom_reference_data.json"

################################################################################
#  OPTIONS ARE SET BY USER IN THIS FILE AS INDICATED BELOW BY:
################################################################################
cmec = True
ext = ".nc"  # ".xml"

# if variables in files are different from the vars[] indicated below
# you can set the varname_in_test_data
# varname_in_test_data

#################################################################
simulation_description_mapping = {
    "creation_date": "creation_date",
    "tracking_id": "tracking_id",
}

regions_specs = json.load(open(os.path.join(para_path, para_reg_file)))

# USER CUSTOMIZED REGIONS
if regional == "y":
    regions = {
        "rltcre": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "rstcre": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "rlut": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "rlutcs": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "rsdt": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "rtmt": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "rmt": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "rlds": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "rldscs": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "rlus": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "rsds": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "rsdscs": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "rsus": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "rsuscs": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "rsut": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "rsutcs": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "hfls": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "hfss": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "ua": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "ta": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "pr": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "prsn": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "prw": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "ts": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "tas": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "tauu": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "tauv": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "psl": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "sfcWind": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "evspsbl": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "ta200": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "ta850": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "ua200": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "ua850": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "va200": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "va850": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "zg500": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "zg700": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "wa500": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "clivi": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "clwvi": [
            "global",
            "land",
            "ocean",
            "ocean_20S20N",
            "20S20N",
            "NH",
            "SH",
            "ocean_SH",
            "land_SH",
            "90S50S",
            "50S20S",
        ],
        "tos": [
            "ocean",
            "ocean_20S20N",
            "ocean_NH",
            "ocean_SH",
            "ocean_90S50S",
            "ocean_50S20S",
        ],
        "sic": [
            "ocean",
            "ocean_20S20N",
            "ocean_NH",
            "ocean_SH",
            "ocean_90S50S",
            "ocean_50S20S",
        ],
        "sos": [
            "ocean",
            "ocean_20S20N",
            "ocean_NH",
            "ocean_SH",
            "ocean_90S50S",
            "ocean_50S20S",
        ],
    }

if regional == "n":
    default_regions = ["global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"]
    regions = {
        None: [
            None,
        ],
    }
    regions = {
        "rlut": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "rlutcs": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "rtmt": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "rltcre": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "rstcre": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "hfls": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "hfss": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "tauu": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "tauv": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "sfcWind": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "psl": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "tas": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "ts": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "pr": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "U850": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "U200": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "ta200": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "ta850": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
        "zg500": [None, "global", "land", "NH", "SH", "NHEX", "SHEX", "TROPICS"],
    }

## USER CAN CUSTOMIZE REGIONS VALUES NAMES
regions_values = {"land": 100.0, "ocean": 0.0}

# INTERPOLATION OPTIONS
target_grid = "2.5x2.5"  # OPTIONS: '2.5x2.5' or an actual cdms2 grid object
targetGrid = target_grid
target_grid_string = "2p5x2p5"
regrid_tool = "esmf"  # "regrid2"  #'esmf' #'regrid2' # OPTIONS: 'regrid2','esmf'
regrid_method = "regrid2"  #'conservative'  #'linear'  # OPTIONS: 'linear','conservative', only if tool is esmf
regrid_tool_ocn = "esmf"  # OPTIONS: "regrid2","esmf"
regrid_method_ocn = (
    "conservative"  # OPTIONS: 'linear','conservative', only if tool is esmf
)

#######################################
metrics_output_path = os.path.join(
    output_path, "metrics_results", "mean_climate", MIP, exp, "%(case_id)/"
)  # All SAME FILE
########################################
# DIRECTORY WHERE TO PUT INTERPOLATED MODELS' CLIMATOLOGIES
diagnostics_output_path = os.path.join(
    output_path,
    "diagnostic_results",
    "interpolated_model_clims",
    MIP,
    exp,
    "%(case_id)/",
)

# if regional == "n":
#    num_workers = 20  # 17
#    granularize = ["vars"]
